WoodSens/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from core.views import IndexView, ProductDetailView, CategoryDetailView, GalleryListView, OnSaleListView, \
    TourDetailView, SearchListView, CustomPageDetailView, ReviewsListView, AboutDetailView, ContactDetailView
from core.sitemaps import CategorySitemap, ProductSitemap, PageSitemap


sitemaps = {
    'categories': CategorySitemap,
    'products': ProductSitemap,
    'pages': PageSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet')),
    path('redactor/', include('redactor.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('', IndexView.as_view(), name='index'),
    path('page/<slug:slug>/', CustomPageDetailView.as_view(), name='custom_page'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product'),
    path('category/<slug:category_popular>/popular/', CategoryDetailView.as_view(), name='category_popular'),
    path('category/<path:path>/', CategoryDetailView.as_view(), name='category'),
    path('gallery/', GalleryListView.as_view(), name='gallery'),
    path('on-sale/', OnSaleListView.as_view(), name='on_sale'),
    path('tour/', TourDetailView.as_view(), name='tour'),
    path('search/', SearchListView.as_view(), name='search'),
    path('reviews/', ReviewsListView.as_view(), name='reviews'),
    path('about/', AboutDetailView.as_view(), name='about'),
    path('contact/', ContactDetailView.as_view(), name='contact'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.TOOLBAR_ENABLED:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from django.utils.functional import cached_property
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from solo.models import SingletonModel
from colorful.fields import RGBColorField

from .mixins import SEOModelMixin
from .helpers import unique_slugify, upload_common_images_to, upload_product_images_to, upload_gallery_images_to


class Category(MPTTModel, SEOModelMixin):
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,
                            on_delete=models.SET_NULL)

    home_box_image = models.ImageField(blank=True, null=True, upload_to=upload_common_images_to)
    home_box_text = models.CharField(max_length=200, blank=True)
    banner = models.ImageField(blank=True, null=True, upload_to=upload_common_images_to)

    content_title_top = models.CharField(max_length=200, blank=True, verbose_name='Title Top')
    content_text_top = models.TextField(blank=True, verbose_name='Text Top')

    # content_title_bottom = models.CharField(max_length=200, blank=True, verbose_name='Title Bottom')
    # content_text_bottom = models.TextField(blank=True, verbose_name='Text Bottom')

    # order = models.PositiveIntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        unique_slugify(self, self.name)
        super().save(*args, **kwargs)

    @cached_property
    def get_absolute_url(self):
        path = '/'.join([x.slug for x in self.get_ancestors(include_self=True)])
        return reverse('category', args=[path])

    class Meta:
        # ordering = ('order',)
        verbose_name_plural = 'Categories'
        unique_together = (('name', 'parent',),)

    def get_banner_image(self):
        if self.banner:
            return self.banner.url

        if not self.is_root_node():
            return self.get_root().get_banner_image()

        return ''


# NAVI


class Header(SingletonModel):
    header_color_sides = RGBColorField(default='#01123e')
    header_color_center = RGBColorField(default='#306da3')

    def __str__(self):
        return 'Header'

    class Meta:
        verbose_name = 'Header'


class TopNavigationItem(MPTTModel):
    name = models.CharField(max_length=50, unique=False)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,
                            on_delete=models.SET_NULL)
    page = models.ForeignKey('pages.Page', blank=True, null=True, on_delete=models.SET_NULL)
    url = models.CharField(max_length=300, blank=True, verbose_name='Or URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        if self.page_id is not None:
            return self.page.get_absolute_url()
        elif self.url:
            return self.url
        else:
            return '#'

    class Meta:
        verbose_name = 'Navigation Item'
        unique_together = (('name', 'parent',),)


class Product(SEOModelMixin):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    description = models.TextField(blank=True)
    sku = models.CharField(max_length=70, blank=True, verbose_name='SKU')
    categories = TreeManyToManyField(Category, related_name='products')

    price_regular = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True, verbose_name='Regular price')
    price_sale = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True, verbose_name='Sale price')

    is_popular = models.BooleanField(default=False, verbose_name='Popular')
    is_on_sale = models.BooleanField(default=False, verbose_name='On sale')
    is_coming_soon = models.BooleanField(default=False, verbose_name='Coming soon')

    width = models.FloatField(blank=True, null=True)
    height = models.FloatField(blank=True, null=True)
    depth = models.FloatField(blank=True, null=True)

    created_date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        unique_slugify(self, self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_featured_image(self):
        if self.images.exists():
            return self.images.first()
        return None

    def get_breadcrumb(self):
        return self.categories.all().order_by('level')

    def get_absolute_url(self):
        return reverse('product', args=[self.slug])

    class Meta:
        ordering = ('-is_popular', '-created_date',)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=upload_product_images_to)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta:
        ordering = ('order',)


class SiteConfiguration(SingletonModel):
    google_maps_api_key = models.CharField(blank=True, max_length=200)
    footer_scripts = models.TextField(blank=True, help_text="Don't forget to wrap code in &lt;script&gt; tag")
    email_list = models.TextField(blank=True, help_text="One email per line")
    vanities_link = models.URLField(blank=True)

    contact_phone = models.CharField(max_length=100, blank=True)
    contact_address = models.TextField(blank=True)
    # contact_email = models.EmailField(blank=True)
    working_hours = models.TextField(blank=True)

    facebook_link = models.URLField(blank=True)
    twitter_link = models.URLField(blank=True)
    google_plus_link = models.URLField(blank=True)
    houzz_link = models.URLField(blank=True)

    disclaimer = models.TextField(blank=True)

    def __str__(self):
        return 'Site Configuration'

    class Meta:
        verbose_name = 'Site Configuration'


############################
############################


class Footer(SingletonModel):
    copyright_text = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return 'Footer'

    class Meta:
        verbose_name = 'Footer'


class AbstractFooterColumnItem(models.Model):
    name = models.CharField(max_length=50)
    page = models.ForeignKey('pages.Page', blank=True, null=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=300, blank=True, verbose_name='Or URL')
    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    footer = models.ForeignKey(Footer, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True
        ordering = ('order',)

    def get_absolute_url(self):
        if self.page_id is not None:
            return self.page.get_absolute_url()
        elif self.url:
            return self.url
        else:
            return '#'


class FooterColumn1Item(AbstractFooterColumnItem):

    class Meta(AbstractFooterColumnItem.Meta):
        verbose_name = 'Footer Column 1 Item'
        verbose_name_plural = 'Footer Column 1 Items'


class FooterColumn2Item(AbstractFooterColumnItem):

    class Meta(AbstractFooterColumnItem.Meta):
        verbose_name = 'Footer Column 2 Item'
        verbose_name_plural = 'Footer Column 2 Items'


###############


class Popup(SingletonModel):
    enabled = models.BooleanField(default=True)
    image = models.ImageField(blank=True, null=True, upload_to=upload_common_images_to)
    button_text = models.CharField(max_length=50, blank=True)
    button_page = models.ForeignKey('pages.Page', blank=True, null=True, on_delete=models.SET_NULL)
    button_url = models.CharField(max_length=300, blank=True, verbose_name='Or URL')
    delay = models.IntegerField(default=3, help_text='In seconds')

    def __str__(self):
        return 'Popup'

    class Meta:
        verbose_name = 'Popup'

    def get_absolute_url(self):
        if self.button_page_id is not None:
            return self.button_page.get_absolute_url()
        elif self.button_url:
            return self.button_url
        else:
            return '#'



core/views.py
import json

from django.core import paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, Http404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, FormView

from pages.models import CustomPage, HomePage, GalleryPage, GalleryImage, OnSalePage, TourPage, ReviewsPage, Review, \
    AboutPage, ContactPage
from .forms import ContactForm
from .models import Category, Product


class IndexView(TemplateView):
    template_name = 'core/pages/index.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        home_page_solo = HomePage.get_solo()
        tour_page_solo = TourPage.get_solo()
        ctx['solo'] = home_page_solo
        ctx['reviews'] = Review.objects.all()
        ctx['contact_form'] = ContactForm()
        ctx['images_json'] = json.dumps({'images': [x.image.url for x in GalleryImage.objects.all()]})
        ctx['video_tour_url'] = tour_page_solo.video_tour_url
        ctx['virtual_tour_url'] = tour_page_solo.virtual_tour_url
        return ctx


class ProductDetailView(DetailView):
    model = Product
    template_name = 'core/pages/product_detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        self.object = self.get_object()
        MAX_RELATED_PRODUCTS = 4
        subcategory = self.object.categories.filter(level=1)
        if subcategory.exists():
            # Get related products from subcategory
            category = subcategory.first()
            related_products = category.products.all().exclude(id=self.object.id)[:MAX_RELATED_PRODUCTS]
            ctx['related_products'] = related_products
        return ctx


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'core/pages/category_detail.html'
    paginate_products_by = 12

    def dispatch(self, request, *args, **kwargs):
        self.category_popular_slug = kwargs.get('category_popular')
        self.category_path = kwargs.get('path')
        self.page = request.GET.get('page')
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if self.category_popular_slug:
            return get_object_or_404(self.model, slug=self.category_popular_slug)  # TODO select related
        elif self.category_path:
            last_slug = self.category_path.split('/')[-1]
            return get_object_or_404(self.model, slug=last_slug)
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['reviews'] = Review.objects.all().order_by('?')[:2]
        products = self.get_object().products.all()

        if self.category_popular_slug:
            ctx['is_popular'] = True
            products = products.filter(is_popular=True)

        products_paginator = paginator.Paginator(products, self.paginate_products_by)
        try:
            products_page_obj = products_paginator.page(self.page)
        except (paginator.PageNotAnInteger, paginator.EmptyPage):
            products_page_obj = products_paginator.page(1)

        ctx['products'] = products_page_obj
        return ctx


class GalleryListView(ListView):
    model = GalleryImage
    template_name = 'core/pages/gallery_list.html'
    # paginate_by = 20
    context_object_name = 'images'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['solo'] = GalleryPage.get_solo()
        return ctx


class OnSaleListView(ListView):
    model = Product
    template_name = 'core/pages/on_sale_list.html'
    paginate_by = 16
    context_object_name = 'products'

    def get_queryset(self):
        return super().get_queryset().filter(is_on_sale=True)

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['solo'] = OnSalePage.get_solo()
        return ctx


class TourDetailView(DetailView):
    model = TourPage
    template_name = 'core/pages/tour_detail.html'

    def get_object(self, queryset=None):
        return self.model.get_solo()


class SearchListView(ListView):
    model = Product
    template_name = 'core/pages/search_list.html'
    paginate_by = 16
    context_object_name = 'products'

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            q = q.strip()
            qs = qs.filter(Q(name__icontains=q) | Q(description__icontains=q) | Q(sku__icontains=q))
            return qs
        else:
            raise Http404


class CustomPageDetailView(DetailView):
    model = CustomPage
    template_name = 'core/pages/custom_page_detail.html'
    context_object_name = 'page'


class ReviewsListView(ListView):
    model = Review
    template_name = 'core/pages/reviews_list.html'
    context_object_name = 'reviews'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['solo'] = ReviewsPage.get_solo()
        return ctx


class AboutDetailView(DetailView):
    model = AboutPage
    template_name = 'core/pages/about_detail.html'
    context_object_name = 'page'

    def get_object(self, queryset=None):
        return self.model.get_solo()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['images_json'] = json.dumps({'images': [x.image.url for x in GalleryImage.objects.all()]})
        return ctx


class ContactDetailView(FormView):
    form_class = ContactForm
    template_name = 'core/pages/contact_detail.html'
    success_url = reverse_lazy('custom_page', kwargs={'slug': 'thank-you'})

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page'] = ContactPage.get_solo()
        return ctx

core/templates/core/base_html.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block seo_description %}{% endblock %}">
    <meta name="keywords" content="{% block seo_keywords %}{% endblock %}">
    <title>{% block seo_title %}Woodsenseinteriors{% endblock %}</title>
            <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" >
    <link href="{% static 'lib/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/jquery-mmenu/jquery.mmenu.all.css' %}" rel="stylesheet">
    <link href="{% static 'lib/fancybox/jquery.fancybox.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo:100,300,500|Open+Sans:300,300i,400,600,700"
          rel="stylesheet">
    {% block include_css %}{% endblock %}
    <link href="{% static 'css/base.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="wrapper">
    {% block body_block %}{% endblock %}
</div>

<script src="{% static 'lib/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'lib/popper/popper.min.js' %}"></script>
<script src="{% static 'lib/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'lib/jquery-mmenu/jquery.mmenu.all.js' %}"></script>
<script src="{% static 'lib/underscore/underscore-min.js' %}"></script>
<script src="{% static 'lib/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/base.min.js' %}"></script>
{% block include_js %}{% endblock %}
{% block footer_scripts %}{% endblock %}
</body>
</html>

core/templates/core/base_template.html
{% extends 'core/base_html.html' %}
{% load static %}
{% load solo_tags %}
{% load extras %}

{% block body_block %}
    {#    <div id="mmwrapper">#}
{#    {% get_solo 'core.SiteConfiguration' as site_config %}#}
    {% get_solo 'core.Header' as header_solo %}
    {% get_solo 'core.Footer' as footer_solo %}
    {% get_solo 'core.Popup' as popup_solo %}
    {% get_root_categories as root_categories %}

    <style>
        {% with color_sides=header_solo.header_color_sides color_center=header_solo.header_color_center %}
            header.header {
                background: {{ color_sides }};
                background: -moz-linear-gradient(left, {{ color_sides }} 0%, {{ color_center }} 50%, {{ color_sides }} 100%);
                background: -webkit-gradient(left top, right top, color-stop(0%, {{ color_sides }}), color-stop(50%, {{ color_center }}), color-stop(100%, {{ color_sides }}));
                background: -webkit-linear-gradient(left, {{ color_sides }} 0%, {{ color_center }} 50%, {{ color_sides }} 100%);
                background: -o-linear-gradient(left, {{ color_sides }} 0%, {{ color_center }} 50%, {{ color_sides }} 100%);
                background: -ms-linear-gradient(left, {{ color_sides }} 0%, {{ color_center }} 50%, {{ color_sides }} 100%);
                background: linear-gradient(to right, {{ color_sides }} 0%, {{ color_center }} 50%, {{ color_sides }} 100%);
                filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#01123e', endColorstr='#01123e', GradientType=1);
            }
        {% endwith %}
    </style>
    <header class="header">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-auto text-center mb-3 mb-lg-0">
                    <a href="{% url 'index' %}">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </a>
                </div>

                <div class="col-md">
                    <div class="top d-flex flex-wrap align-items-center justify-content-center justify-content-lg-end mb-3">
                        <a href="{{ site_config.facebook_link|default:'#' }}" target="_blank"
                           class="d-none d-md-inline">
                            <img src="{% static 'img/like.png' %}" alt=""></a>
                        <a href="#" id="btn-top-search" data-toggle="popover">
                            <img src="{% static 'img/t-search.png' %}" alt="" class="ml-md-3 mr-3"></a>
                        <br class="d-none d-md-block">
                        <h4 class="mb-0">
                            <span class="">|</span> Call Us: <a
                                href="tel:{{ site_config.contact_phone }}"><strong>{{ site_config.contact_phone }}</strong></a>
                        </h4>
                    </div>
                    <div id="main-menu" class="bottom">
                        {% get_top_menu %}
                    </div>
                </div>

                <div class="col-md-auto">
                    <div class="form-row align-items-center">
                        <div class="col-auto d-none d-lg-block">
                            <a href="{% url 'on_sale' %}"><img src="{% static 'img/onsale.png' %}" alt=""></a>
                        </div>
                        {% if site_config.vanities_link %}
                            <div class="col-auto d-none d-lg-block">
                                <a target="_blank" href="{{ site_config.vanities_link }}">
                                    <img src="{% static 'img/vnm.png' %}" alt=""></a>
                            </div>
                        {% endif %}
                        <div class="col-auto ml-auto d-lg-none">
                            <a href="#main-menu" class="btn btn-outline-light ml-3"><i class="fa fa-fw fa-bars"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="position-relative">
        {% get_categories_submenu_desktop root_categories %}
    </div>

    {% block template_body_block %}{% endblock %}

    <footer class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-xl-6 mb-3 mb-lg-0">
                    <div class="row">
                        <div class="col-md-4 mb-3 mb-md-0">
                            <p class="fhe">Categories</p>
                            <ul>
                                {% for category in root_categories %}
                                    <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-md-4 mb-3 mb-md-0">
                            <p class="fhe">Offers</p>
                            <ul>
                                {% for item in footer_solo.footercolumn1item_set.all %}
                                    <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <p class="fhe">Policies</p>
                            <ul>
                                {% for item in footer_solo.footercolumn2item_set.all %}
                                    <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-xl-6">
                    <p class="fhe">Stay Connected</p>
                    <p>Subscribe now and get a latest updates to our deals and offers.</p>
                    <form action="https://woodsenseinteriors.us18.list-manage.com/subscribe/post?u=852fcb2ff6758841810e1befc&id=bb70fe5423"
                          method="POST" name="mc-embedded-subscribe-form">
                        <div class="form-row mb-3">
                            <div class="col-md-7 mb-3 mb-md-0">
                                <input type="email" name="EMAIL" class="form-control form-control-lg"
                                       placeholder="Enter Your Email Address">
                                <input type="text" class="hp" name="b_852fcb2ff6758841810e1befc_bb70fe5423"
                                       tabindex="-1" value="">
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-block btn-outline-light btn-lg">Sign up now!
                                </button>
                            </div>
                        </div>
                    </form>
                    <p class="fhe">Follow us</p>
                    {% if site_config.facebook_link %}
                        <a href="{{ site_config.facebook_link }}" target="_blank"><img class="mr-2"
                                                                                       src="{% static 'img/fb.png' %}"></a>
                    {% endif %}
                    {% if site_config.twitter_link %}
                        <a href="{{ site_config.twitter_link }}" target="_blank"><img class="mr-2"
                                                                                      src="{% static 'img/tw.png' %}"></a>
                    {% endif %}
                    {% if site_config.google_plus_link %}
                        <a href="{{ site_config.google_plus_link }}" target="_blank"><img class="mr-2"
                                                                                          src="{% static 'img/gp.png' %}"></a>
                    {% endif %}
                    {% if site_config.houzz_link %}
                        <a href="{{ site_config.houzz_link }}" target="_blank"><img src="{% static 'img/houzz.png' %}"></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </footer>

    <footer class="footer-bottom">
        <div class="container">
            <p class="m-0 text-center text-md-right text-light">{{ footer_solo.copyright_text }}</p>
        </div>
    </footer>

    {% if popup_solo.enabled %}
        <div class="modal fade" id="modalTimer" tabindex="-1" role="dialog" aria-labelledby="modalTimerLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {% if popup_solo.image %}
                            <img src="{{ popup_solo.image.url }}" class="img-fluid" alt="">
                        {% endif %}
                    </div>
                    <div class="modal-footer justify-content-center">
                        <a href="{{ popup_solo.get_absolute_url }}" class="btn btn-lg btn-warning btn-orange px-5">
                            {{ popup_solo.button_text|default:'' }}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {#    </div>#}
{% endblock %}

{% block include_js %}
    {% get_solo 'core.Popup' as popup_solo %}
    {% if popup_solo.enabled %}
        <script>
            var p_delay = {{ popup_solo.delay }};
            if (getCookie('popup') != 1) {
                setCookie('popup', 1, 0.5);
                setTimeout(function () {
                    $('#modalTimer').modal('show');
                }, p_delay * 1000);
            }
        </script>
    {% endif %}
{% endblock %}

{% block footer_scripts %}
{#    {% get_solo 'core.SiteConfiguration' as site_config %}#}
    {{ site_config.footer_scripts|safe }}
{% endblock %}